// 🎬 PromptVideo.tsx — Core Remotion Composition
// Generated by Remotion Prompt Studio
// https://github.com/rifaterdemsahin/remotion-with-a-prompt

import React from "react";
import {
  AbsoluteFill,
  useCurrentFrame,
  useVideoConfig,
  spring,
  interpolate,
  Sequence,
  Img,
} from "remotion";

// ── Props ──────────────────────────────────────────────────────────────────
interface PromptVideoProps {
  prompt?: string;
  imageUrl?: string;
  text?: string;
  backgroundColor?: string;
  animation?: "fade" | "slide" | "zoom" | "bounce" | "rotate" | "typewriter";
  slideDirection?: "left" | "right" | "up" | "down";
  textColor?: string;
  hasGradientText?: boolean;
}

// ── Component ─────────────────────────────────────────────────────────────
export const PromptVideo: React.FC<PromptVideoProps> = ({
  prompt = "Fade in logo with text",
  imageUrl,
  text = "Hello World",
  backgroundColor = "#0d1117",
  animation = "fade",
  slideDirection = "left",
  textColor = "white",
  hasGradientText = false,
}) => {
  const frame = useCurrentFrame();
  const { fps, durationInFrames } = useVideoConfig();

  // ── Fade Animation ───────────────────────────────────────────────────────
  const fadeOpacity = spring({
    fps,
    frame,
    config: { damping: 200, stiffness: 80 },
    durationInFrames: Math.round(fps * 0.8),
  });

  // ── Slide Animation ──────────────────────────────────────────────────────
  const slideProgress = spring({
    fps,
    frame,
    config: { damping: 100, stiffness: 60, mass: 0.8 },
    durationInFrames: Math.round(fps * 1.0),
  });

  const getTranslate = () => {
    const from = { left: -120, right: 120, up: -80, down: 80 }[slideDirection];
    const value = interpolate(slideProgress, [0, 1], [from, 0]);
    const axis = slideDirection === "left" || slideDirection === "right" ? "X" : "Y";
    return `translate${axis}(${value}px)`;
  };

  // ── Zoom Animation ───────────────────────────────────────────────────────
  const scaleValue = spring({
    fps,
    frame,
    config: {
      damping: animation === "bounce" ? 40 : 150,
      stiffness: animation === "bounce" ? 80 : 60,
    },
    durationInFrames: Math.round(fps * 0.6),
    from: 0,
    to: 1,
  });

  // ── Rotate Animation ─────────────────────────────────────────────────────
  const rotation = interpolate(
    frame,
    [0, Math.round(fps * 0.5)],
    [180, 0],
    { extrapolateRight: "clamp" }
  );

  // ── Typewriter Animation ─────────────────────────────────────────────────
  const charsToShow = Math.floor(
    interpolate(frame, [0, fps * 1.5], [0, text.length], {
      extrapolateRight: "clamp",
    })
  );
  const displayText = text.slice(0, charsToShow);

  // ── Fade Out ──────────────────────────────────────────────────────────────
  const fadeOutOpacity = interpolate(
    frame,
    [durationInFrames - fps * 0.5, durationInFrames],
    [1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" }
  );

  // ── Compute final transform + opacity ────────────────────────────────────
  const getTransform = (): string => {
    switch (animation) {
      case "slide": return getTranslate();
      case "zoom":
      case "bounce": return `scale(${scaleValue})`;
      case "rotate": return `rotate(${rotation}deg)`;
      default: return "none";
    }
  };

  const getOpacity = (): number => {
    const base = animation === "fade" ? fadeOpacity : 1;
    return base * fadeOutOpacity;
  };

  const textStyle: React.CSSProperties = {
    fontSize: 72,
    fontWeight: "bold",
    color: hasGradientText ? "transparent" : textColor,
    textAlign: "center",
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    textShadow: "0 4px 24px rgba(0,0,0,0.5)",
    maxWidth: "80%",
    transform: getTransform(),
    opacity: getOpacity(),
    ...(hasGradientText && {
      background: "linear-gradient(90deg, #ff79c6, #bd93f9, #50fa7b)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
    }),
  };

  return (
    <AbsoluteFill
      style={{
        backgroundColor,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "column",
        gap: 32,
      }}
    >
      {/* Image Layer */}
      {imageUrl && (
        <Sequence from={0}>
          <AbsoluteFill style={{ display: "flex", alignItems: "center", justifyContent: "center" }}>
            <Img
              src={imageUrl}
              style={{
                width: 320,
                height: 320,
                objectFit: "contain",
                borderRadius: 16,
                transform: getTransform(),
                opacity: getOpacity(),
              }}
            />
          </AbsoluteFill>
        </Sequence>
      )}

      {/* Text Layer */}
      <div style={{ position: "absolute", bottom: "20%", left: 0, right: 0, textAlign: "center" }}>
        <div style={textStyle}>
          {animation === "typewriter" ? displayText : text}
        </div>
      </div>

      {/* Prompt watermark (remove in production) */}
      <div
        style={{
          position: "absolute",
          top: 16,
          left: 16,
          fontSize: 12,
          color: "rgba(255,255,255,0.3)",
          fontFamily: "monospace",
        }}
      >
        prompt: {prompt.slice(0, 60)}
      </div>
    </AbsoluteFill>
  );
};
